version: 1.0.{build}
install:
  - cinst nodejs -y
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"
  - cmd: npm install -g grunt-cli bower
build_script:
- ps: >-
    $kDirectory = Join-Path -ChildPath .k\ -Path $env:USERPROFILE
    
    $env:Path += ";" + $kDirectory + "bin"
    
    kvm upgrade
    
    kpm restore .\src
    
    kpm build .\src