version: 1.0.{build}
install:
  - powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"
  - npm install -g gulp bower
  
build_script: powershell -NoProfile -ExecutionPolicy unrestricted -File build.ps1