install:
  - ps:  -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"
build_script:
  - build.ps1

# to disable automatic tests 
test: off