version: 1.0.{build}
install:
  - powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - npm install -g gulp bower
  
build_script: powershell -NoProfile -ExecutionPolicy unrestricted -File build.ps1